/**
 * Configuración visual y de comportamiento para cada estado del Patrón State.
 * Fuente única de verdad que usan todos los componentes.
 */
export const STATE_CONFIG = {
  AVAILABLE: {
    color:      '#4ADE80',
    background: 'rgba(74, 222, 128, 0.13)',
    orbColor:   '#4ADE80',
    badge:      'DISPONIBLE',
    label:      'Disponible',
    description:'Estación operativa. Acerca tu EV al área de carga.',
    buttonText: 'Conectar Vehículo',
    buttonBg:   '#F97316',
    apiEndpoint:'POST /api/station/connect',
    stageTitle: 'Listo para Cargar',
    stageSub:   'Conecta tu EV al puerto de carga',
    journeyStep: 1,
    showErrorBtn:true,
    showMaintBtn:true,
  },
  CONNECTING: {
    color:      '#60A5FA',
    background: 'rgba(96, 165, 250, 0.13)',
    orbColor:   '#60A5FA',
    badge:      'CONECTANDO',
    label:      'Conectando',
    description:'Handshake OCPP en progreso. Negociando parámetros de carga.',
    buttonText: 'Iniciar Transferencia',
    buttonBg:   '#60A5FA',
    apiEndpoint:'POST /api/station/start-charging',
    stageTitle: 'Conectando EV...',
    stageSub:   'Protocolo OCPP en progreso',
    journeyStep: 2,
    showErrorBtn:true,
    showMaintBtn:false,
  },
  CHARGING: {
    color:      '#F97316',
    background: 'rgba(249, 115, 22, 0.13)',
    orbColor:   '#F97316',
    badge:      'CARGANDO',
    label:      'Cargando',
    description:'Flujo DC activo. Inversor operando a máxima eficiencia.',
    buttonText: 'Completar Carga',
    buttonBg:   '#4ADE80',
    apiEndpoint:'POST /api/station/complete-charge',
    stageTitle: 'Cargando...',
    stageSub:   'Transferencia de energía DC activa',
    journeyStep: 3,
    showErrorBtn:true,
    showMaintBtn:false,
  },
  COMPLETED: {
    color:      '#2DD4BF',
    background: 'rgba(45, 212, 191, 0.13)',
    orbColor:   '#2DD4BF',
    badge:      'COMPLETADO',
    label:      '¡Carga Completa!',
    description:'Batería al 100%. Desconecta el cable para finalizar.',
    buttonText: 'Desconectar EV ✓',
    buttonBg:   '#2DD4BF',
    apiEndpoint:'POST /api/station/disconnect',
    stageTitle: '¡Batería Completa!',
    stageSub:   'Desconecta el cable para finalizar',
    journeyStep: 4,
    showErrorBtn:false,
    showMaintBtn:false,
  },
  ERROR: {
    color:      '#F87171',
    background: 'rgba(248, 113, 113, 0.13)',
    orbColor:   '#F87171',
    badge:      'ERROR',
    label:      'Error del Sistema',
    description:'Falla detectada. Reset manual requerido por el operario técnico.',
    buttonText: 'Resetear Sistema',
    buttonBg:   '#F87171',
    apiEndpoint:'POST /api/station/reset-error',
    stageTitle: 'Error del Sistema',
    stageSub:   'Contacta al soporte técnico',
    journeyStep: 0,
    showErrorBtn:false,
    showMaintBtn:false,
  },
  MAINTENANCE: {
    color:      '#A78BFA',
    background: 'rgba(167, 139, 250, 0.13)',
    orbColor:   '#A78BFA',
    badge:      'MANTENIMIENTO',
    label:      'Mantenimiento',
    description:'Estación fuera de servicio por mantenimiento preventivo.',
    buttonText: 'Finalizar Mantenimiento',
    buttonBg:   '#A78BFA',
    apiEndpoint:'POST /api/station/end-maintenance',
    stageTitle: 'En Mantenimiento',
    stageSub:   'Estación temporalmente no disponible',
    journeyStep: 0,
    showErrorBtn:false,
    showMaintBtn:false,
  },
};

/** Etiquetas de los pasos del journey para el usuario */
export const JOURNEY_LABELS = ['Llegar', 'Conectar', 'Cargar', 'Listo ✓'];
